export const ReportActionsTypes = {
    
    REDUCER_SET_REPORT_REVIEW: "REDUCER_SET_REPORT_REVIEW",
    REDUCER_SET_REPORT_CATEGORY: "REDUCER_SET_REPORT_CATEGORY",
    REDUCER_SET_REPORT_ERROR: "REDUCER_SET_REPORT_ERROR",
    
    REDUCER_SET_REPORT_REVIEW_CATEGORY: "REDUCER_SET_REPORT_REVIEW_CATEGORY",
    REDUCER_RESET_REPORT: "REDUCER_RESET_REPORT",
}
