export const QuizActionsTypes = {
    REDUCER_SET_ACTIVE: "REDUCER_SET_ACTIVE",
    REDUCER_SET_CATEGORY: "REDUCER_SET_CATEGORY",
    REDUCER_SET_QUESTION_NUMBER: "REDUCER_SET_QUESTION_NUMBER",
    REDUCER_SET_DIFFICULTY: "REDUCER_SET_DIFFICULTY",
    REDUCER_SET_PROMOTION: "REDUCER_SET_PROMOTION",
    REDUCER_SET_QUESTION_DATAS: "REDUCER_SET_QUESTION_DATAS",
    REDUCER_SET_CURRENT_QUESTION: "REDUCER_SET_CURRENT_QUESTION",
    REDUCER_SET_CURRENT_OPTIONS: "REDUCER_SET_CURRENT_OPTIONS",
    REDUCER_SET_TOKEN: "REDUCER_SET_TOKEN",

    REDUCER_SET_QUIZ_ERROR: "REDUCER_SET_QUIZ_ERROR",
    REDUCER_RESET_QUIZ: "REDUCER_RESET_QUIZ",

    SAGA_FETCH_NEW_QUESTION: "SAGA_FETCH_NEW_QUESTION",
    SAGA_CHECK_ANSWER: "SAGA_CHECK_ANSWER",
    SAGA_RIGHT_ANSWERS_ACTIONS: "SAGA_RIGHT_ANSWERS_ACTIONS",
    SAGA_WRONG_ANSWERS_ACTIONS: "SAGA_WRONG_ANSWERS_ACTIONS",
    SAGA_GET_CURRENT_OPTIONS: "SAGA_GET_CURRENT_OPTIONS",
    SAGA_GO_TO_NEXT_QUESTION: "SAGA_GO_TO_NEXT_QUESTION",
    SAGA_FINISH_QUIZ: "SAGA_FINISH_QUIZ",
    SAGA_RESUME_QUIZ: "SAGA_RESUME_QUIZ",
}
