export const UserActionsTypes = {
    
    REDUCER_SET_USER: "REDUCER_SET_USER",
    REDUCER_SET_AUTH_ERROR: "REDUCER_SET_AUTH_ERROR",
    REDUCER_SET_PERSISTENCE: "REDUCER_SET_PERSISTENCE",
    REDUCER_SET_THEME: "REDUCER_SET_THEME",

    REDUCER_SIGN_IN_SUCCESS: "REDUCER_SIGN_IN_SUCCESS",
    REDUCER_SIGN_IN_FAILURE: "REDUCER_SIGN_IN_FAILURE",
    REDUCER_SIGN_OUT_SUCCESS: "REDUCER_SIGN_OUT_SUCCESS",
    REDUCER_SIGN_OUT_FAILURE: "REDUCER_SIGN_OUT_FAILURE",
    REDUCER_SIGN_UP_FAILURE: "REDUCER_SIGN_UP_FAILURE",
    REDUCER_RESET_THEME: "REDUCER_RESET_THEME",
    REDUCER_SET_USER_ERROR: "REDUCER_SET_USER_ERROR",

    SAGA_SET_USER_AUTH: "SAGA_SET_USER_AUTH",
    SAGA_SIGN_OUT: "SAGA_SIGN_OUT",
    SAGA_EMAIL_SIGN_IN: "SAGA_EMAIL_SIGN_IN",
    SAGA_EMAIL_SIGN_UP: "SAGA_EMAIL_SIGN_UP",
    SAGA_UPDATE_THEME_ON_DATABASE: "SAGA_UPDATE_THEME_ON_DATABASE",
    SAGA_GET_USER_THEME: "SAGA_GET_USER_THEME",
}
