export const CategoriesActionsTypes = {
    
    REDUCER_SET_CATEGORIES_REPORT: "REDUCER_SET_CATEGORIES_REPORT",
    REDUCER_SET_ALL_CATEGORIES: "REDUCER_SET_ALL_CATEGORIES",
    REDUCER_SET_CATEGORIES_ERROR: "REDUCER_SET_CATEGORIES_ERROR",
    REDUCER_RESET_CATEGORIES: "REDUCER_RESET_CATEGORIES",

    SAGA_GET_CATEGORIES: "SAGA_GET_CATEGORIES",

}
