export const CategoriesActionsTypes = {
    REDUCER_SET_REPORTS: "REDUCER_SET_REPORTS",
    REDUCER_SET_ALL_CATEGORIES: "REDUCER_SET_ALL_CATEGORIES",
    REDUCER_SET_CATEGORIES_ERROR: "REDUCER_SET_CATEGORIES_ERROR",

    SAGA_GET_CATEGORIES: "SAGA_GET_CATEGORIES",
}
